#spring.application.name=example-login-2

spring:
  token:
    secret: ${SECRET_JWT_SECRET:'m#MySecret5339T'}
    issuer: BackendService
---
app:
  upload:
    path: images
---
spring:
  profiles:
    active:
      - prod
---
server:
  port: 8080
spring:
  config:
    activate:
      on-profile:
        - prod
  datasource:
    url: jdbc:postgresql://${SECRET_DB_HOST:localhost}:${SECRET_DB_PORT:5432}/login2
    username: ${SECRET_DB_USERNAME:postgres}
    password: ${SECRET_DB_PASSWORD:Tonpostgresql04}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size:
        5MB
      max-request-size:
        6MB
  kafka:
    bootstrap-servers:
      - ${SECRET_KAFKA_HOST:localhost}:${SECRET_KAFKA_PORT:9092}
    consumer:
      group-id: "my-login-2-app"
  jackson:
    date-format: yyyy-MM-dd
  data:
    redis:
      host: ${SECRET_REDIS_HOST:localhost}
      port: ${SECRET_REDIS_PORT:6379}
  cache:
    type: redis
    redis:
      time-to-live: 1800000
---
spring:
  config:
    activate:
      on-profile:
        - test

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: TonsonDev!
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop # ใช้ create-drop เพื่อให้ schema ถูกสร้างใหม่และลบออกหลังทดสอบ

  jackson:
    date-format: yyyy-MM-dd

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis
    redis:
      time-to-live: 60000

# หาก Kafka ไม่จำเป็นในการทดสอบ สามารถปิดการใช้งานได้
spring.kafka.consumer.auto-offset-reset: earliest
