#spring.application.name=example-login-2

spring:
  token:
    secret: m#MySecret5339T
    issuer: BackendService
---
app:
  upload:
    path: images

---
spring:
  profiles:
    active:
      - dev
---
server:
  port: 1150
spring:
  config:
    activate:
      on-profile:
        - dev
  datasource:
    url: jdbc:postgresql://localhost:5432/login2
    username: postgres
    password: Tonpostgresql04
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  servlet:
    multipart:
      max-file-size:
        5MB
      max-request-size:
        6MB
  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      group-id: "my-login-2-app"
  jackson:
    date-format: yyyy-MM-dd
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 60000
#  mvc:
#    log-request-details: true
#logging:
#  level:
#    org:
#      springframework:
#        web: DEBUG